### ISSUE TITLE
Laravel 11.25.0 introduces vector support and breaks BlueprintTypes::vector 

### ISSUE THREAD

**Issue by keepanitreel** [tpetry/laravel-postgresql-enhanced#100]
Laravel Framework [PR](https://github.com/laravel/framework/pull/52884) adds support for vector and breaks BlueprintTypes::vector

```
Declaration of Tpetry\PostgresqlEnhanced\Schema\BlueprintTypes::vector(string $column, int $dimensions = 1536): Illuminate\Database\Schema\ColumnDefinition must be compatible with Illuminate\Database\Schema\Blueprint::vector($column, $dimensions)
```

**Comment by tpetry** [comment]
This issue is fixed with version `2.0.0`.

The only breaking change to v1 is that the default `$dimensions` value to 1536 had to be dropped. It is now required to always specify it.
