### ISSUE TITLE
Prerequisites

### ISSUE THREAD

**Issue by mitesh0819** [tpetry/laravel-postgresql-enhanced#12]
Please help us with the Prerequisites because for its not compatible with PHP 7.4.9
![image](https://user-images.githubusercontent.com/102866896/161388362-316b9d37-e4ba-4da2-a533-04e66789cc71.png)

**Comment by tpetry** [comment]
This library is designed to require at least PHP 8.0, I am not planning to support any older version.

**Comment by mitesh0819** [comment]
I think we should have support to older version because globally PHP 8.0 is used by only 1%

**Comment by tpetry** [comment]
PHP 8 is used about 40% [0] and PHP 7.4 will not be supported anymore in 7 months and will not receive any security anymore in 9 months [1]. So PHP 7.4 is almost dead, and I will not make any effort to support a PHP version which will be EOL soon. You can just upgrade your version. You are also free to fork the package and change everything to support PHP 7.4.


[0] https://packagist.org/php-statistics
[1] https://www.php.net/supported-versions.php
