### ISSUE TITLE
Laravel 9 TypeError

### ISSUE THREAD

**Issue by LiamKarlMitchell** [tpetry/laravel-postgresql-enhanced#14]
Hi, I'm getting a TypeError trying to use this on Laravel 9.
What am I doing wrong?

```
TypeError 

Illuminate\Database\Migrations\Migration@anonymous(): Argument #1 ($table) must be of type Tpetry\PostgresqlEnhanced\Schema\Blueprint, Illuminate\Database\Schema\Blueprint given, called in
/var/www/html/vendor/laravel/framework/src/Illuminate/Database/Schema/Builder.php on line 256 
```

Migration:
```php
<?php

use Illuminate\Database\Migrations\Migration;
use Tpetry\PostgresqlEnhanced\Schema\Blueprint;
use Tpetry\PostgresqlEnhanced\Schema\Concerns\ZeroDowntimeMigration;
use Tpetry\PostgresqlEnhanced\Support\Facades\Schema;

return new class extends Migration
{
    use ZeroDowntimeMigration;

    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('somethings', function (Blueprint $table) {
        // ...
```

**Comment by LiamKarlMitchell** [comment]
Doing something like this seems to work.
But not as nice as example.

```php
$schema = DB::connection()->getSchemaBuilder();
$schema->blueprintResolver(function($table, $callback) {
    return new Blueprint($table, $callback);
});

$schema->create( //...
```

Note:
```$schema = DB::connection()->getSchemaBuilder();```
Can be shortened to
```$schema = DB::getSchemaBuilder();```

https://stackoverflow.com/questions/22444685/extend-blueprint-class

**Comment by LiamKarlMitchell** [comment]
Possibly also due to this, it seems partial indexes are not working?

```php
$table->index(['user_uuid', DB::raw('created_at DESC')])->where("deleted_at IS NULL");
```

**Comment by tpetry** [comment]
It's working for me. Are you using any other Laravel plugins which extend the database functionalities in your project?

Your partial indexes not working is related to your initial problem. The extended features of my plugin are not loaded, the standard Laravel database implementations are still active.

You don't have to use `DB::raw` in your example, the implementation automatically detects when you want to specify more options for an index:
```php
$table->index(['user_uuid', 'created_at DESC'])->where('deleted_at IS NULL');
```

**Comment by LiamKarlMitchell** [comment]
Thanks @tpetry , I'm not sure what other Laravel plugins would extend the database functionalities, is there some way I need to specify a loading order?

What might I search for to find out?
I have lightsail and nova, laravel scout + meilisearch driver.

Kind regards,

**Comment by tpetry** [comment]
You can create a new minimal Laravel application with a reproducible migration to show the error. Then I can help finding the issue. Currently, there's nothing I can do for you.

**Comment by tpetry** [comment]
Closed as no feedback has been reported for 3 weeks.
