### ISSUE TITLE
uuid default?

### ISSUE THREAD

**Issue by LiamKarlMitchell** [tpetry/laravel-postgresql-enhanced#15]
```
$table->uuid()->primary();
```

Could this be made to set something like this?
DEFAULT uuid_generate_v4()

Currently doing it like this.

```
DB::statement('ALTER TABLE some_table ALTER COLUMN uuid SET DEFAULT uuid_generate_v4();');
```

**Comment by boris-glumpler** [comment]
This works just fine for me:

```
$table->uuid()->primary()->default(DB::raw('uuid_generate_v4()'))
```

**Comment by tpetry** [comment]
My plan is to only extend Laravel with PostgreSQL features, I don't want to change *any* behavior of Laravel. Installing this plugin should not break any existing code because e.g. defaults have been changed. The solution by @boris-glumpler is perfectly valid, and I am doing that way too.
