### ISSUE TITLE
Accept true for lateral join on clause

### ISSUE THREAD

**Issue by PeterRincker** [tpetry/laravel-postgresql-enhanced#19]
I find that some of my lateral join clauses use `true` for the ON clause:

```
JOIN LATERAL (...) ON true
```

So I produce code like:

```
->joinSubLateral($json_table, 'jsn', fn($join) => $join->whereRaw('true'))
```

I was wondering if it would be useful to bake this into the the `joinSubLateral()` method call:
```
if ($first === true && $second === null) {
    $first = fn($join) => $join->whereRaw('true');
}
```

Thanks for the plugin. Cheers!

**Comment by tpetry** [comment]
This idea is nice to reduce the code for some cases. But I want the lateral join methods to have the same API as all other Laravel join methods. I will think a few more days if I want to introduce the special case for the lateral join which is not available for the other join clauses.

**Comment by PeterRincker** [comment]
That is very understandable. Thank you

**Comment by tpetry** [comment]
@PeterRincker Shouldn't the `crossJoinSubLateral` solve your problem exactly? It's a lateral join without any condition. Do you have any queries where this would not work correctly?
