### ISSUE TITLE
Add feature to work with With and with recursive.

### ISSUE THREAD

**Issue by emtudo** [tpetry/laravel-postgresql-enhanced#21]
Excellent package, I've been using it for a long time.

Recently I needed to use with and with recursive and I wanted to use it in the model and not DB.

Would it be possible to add?

I even made it locally for myself, but the code I made I don't think it's feasible to put on the air, but I've extended the service provider and made changes so that Grammer has this method:

```
  /**
     * Compile the select query into SQL.
     *
     * @param \Illuminate\Database\Query\Builder $query
     * @return string
     */
    public function compileSelect(Builder $query)
    {
        $sql = parent::compileSelect($query);

        $withQuery = $query->withQuery;

        if ($withQuery) {
            $withQuery .= ' ';
        }

        return "{$withQuery}{$sql}";
    }
```

Query\Builder I added:

```
   public $withQuery = '';
    public function withQuery($query = null)
    {
        $this->withQuery = $query;

        return $this;
    }
```

It works for me, but it could be better by adding the bindings and making the code better.

**Comment by tpetry** [comment]
It's on my list. I will make it the next item to work on. 😉

**Comment by emtudo** [comment]
that's good!

Thanks!

I will update now!

**Comment by emtudo** [comment]
I thought you already added it.

I will keep waiting

**Comment by tpetry** [comment]
I am not that fast 😅 I will take some days.

**Comment by unansweredocd** [comment]
Looking forward to this, it's the last remaining thing that's preventing me from using the package all the time.

**Comment by tpetry** [comment]
Common Table Expressions are now available with release `0.18.0`. They have been a lot of work as many internal methods had to be patched to correctly support them.

I've slightly changed the API (`withRecursiveExpression` has been merged into `withRecursive`), you can find the current one in the readme.

**Comment by emtudo** [comment]
Thank you very much.

Really appreciate it, I'll try it soon.

**Comment by emtudo** [comment]
It's work very well!

Thanks @tpetry
