### ISSUE TITLE
Returning trait with custom column

### ISSUE THREAD

**Issue by unansweredocd** [tpetry/laravel-postgresql-enhanced#25]
Hey, thanks for creating this. We spoke on Twitter a few times and I said I would try out the driver.

It's awesome, first of all. I do have a question though, the project I'm working on uses the gen_random_uuid() method that postgresql 14 offers. For that, we decided to create a PostgresProcessor that contains the following, so that we always get the uuid when we insert something new in the database. This lets us redirect to a model that was just created, for example, /posts/{uuid}/edit

```php
<?php

namespace App\Database\Query\Processors;

use Illuminate\Database\Query\Builder;

class PostgresProcessor extends \Illuminate\Database\Query\Processors\PostgresProcessor
{
    /**
     * Process an "insert get ID" query.
     *
     * @param  \Illuminate\Database\Query\Builder  $query
     * @param  string  $sql
     * @param  array  $values
     * @param  string|null  $sequence
     * @return int
     */
    public function processInsertGetId(Builder $query, $sql, $values, $sequence = null)
    {
        /** @var \Illuminate\Database\Connection $connection */
        $connection = $query->getConnection();

        $connection->recordsHaveBeenModified();

        $result = $connection->selectFromWriteConnection($sql, $values)[0];

        return (array) $result;
    }
}
```

Note that, the above is used alongside the HasUuid trait that we created so we can make it really easy to get uuids from a freshly created model. 

```php
<?php

namespace App\Traits;

use Illuminate\Database\Eloquent\ModelNotFoundException;
use Illuminate\Database\Query\Expression;
use Illuminate\Http\Response;
use Illuminate\Support\Facades\DB;
use Ramsey\Uuid\Uuid;

/**
 * @method static $this whereUuid($uuid, bool $throwNotFoundOnInvalid = true)
 */
trait HasUuid
{
    public function uuidName()
    {
        return 'uuid';
    }

    /**
     * Insert the given attributes and set the ID on the model.
     *
     * @param  \Illuminate\Database\Query\Builder|\Illuminate\Database\Eloquent\Builder  $query
     * @param  array  $attributes
     * @return void
     */
    protected function insertAndSetId($query, $attributes)
    {
        ['id' => $id, $this->uuidName() => $uuid] = $query->insertGetId($attributes, new Expression("id, {$this->uuidName()}"));

        $this->setAttribute('id', $id);
        $this->setAttribute($this->uuidName(), $uuid);
    }
}
```

My question, would others benefit from having this logic in the driver? I know that you wrote about uuids https://sqlfordevs.io/uuid-prevent-enumeration-attack, so I believe everyone that uses uuids could benefit from this. 

I have the same username on Twitter, so you can always send me a DM if needed. But Github will do just fine also.

If you're not the author of the driver, please also let me know what you think of this idea.

**Comment by tpetry** [comment]
Have you seen the `RefreshDataOnSave` trait? If I understand you correctly it was built for exactly that purpose. It‘s updating the model values (with generated values in the db) on every save automatically without any effort 😉

**Comment by unansweredocd** [comment]
I have not, but I just tried it out and it's exactly what I was looking for. Thank you!
