### ISSUE TITLE
`LIKE` query does not work with `citext`

### ISSUE THREAD

**Issue by jaulz** [tpetry/laravel-postgresql-enhanced#26]
It seems that the `LIKE` query is not working with `citext` columns. I assume that it's related to this piece of code:
https://github.com/laravel/framework/blob/aad4521c6a5c91a8fc0b9acbc2362c281013daea/src/Illuminate/Database/Query/Grammars/PostgresGrammar.php#L42-L47

The column will be casted into `text` and thus any case insensitive search isn't working anymore. Is there any smart way to solve it?

**Comment by tpetry** [comment]
I don't see any way to do it correctly. I'll write a `whereLike` method on the weekend, in the meantime you can use `whereRaw('foo like ?', ['%bar%'])`.

**Comment by jaulz** [comment]
That sounds fantastic, thanks! Does maybe `whereCaseInsensitiveText` make more sense?

**Comment by jaulz** [comment]
Okay, sure, perfect 😊

**Comment by tpetry** [comment]
Released with `0.16.0` 😉

**Comment by jaulz** [comment]
Thanks a lot for your hard work! 😊
