### ISSUE TITLE
tsvector/tsquery column types

### ISSUE THREAD

**Issue by Wulfheart** [tpetry/laravel-postgresql-enhanced#3]
Maybe it can also be beneficial to add `tsvector` and `tsquery` to the supported types for fulltext search. 

https://www.postgresql.org/docs/10/datatype-textsearch.html

**Comment by tpetry** [comment]
Do you know any use case? A tsvector is always dependent on a language, so normally you save the raw text and create a tsvector index for a language. I have never seen a tsvector or tsquery saved in a table. But maybe there are use cases i am not aware of 🤷‍♂️

**Comment by boris-glumpler** [comment]
Not so sure about `tsquery` but I’ve added some generated columns of type `tsvector` in a recent project. Should improve performance rather than doing it on the fly.

**Comment by tpetry** [comment]
A generated tsvector column sounds like a good use case. Bit i am not sure whether an index can be used in this approach. A tsvector is always dependent on a language which can be changed all the time by the `default_text_search_config` setting. I will have to try if this approach is index supportable in the next days. I keep you updated.

**Comment by boris-glumpler** [comment]
In my case, I know that my content will be in English, so I hardcoded that in. Just checked one of my queries with `EXPLAIN ANALYSE` and it did use my `GIN` index.

**Comment by tpetry** [comment]
You are correct, an index can be used without any problem. When someone changes the `default_text_search_config` the stemming of the vector may not be correct for the query, but that's a problem for the developer. 🤷‍♂️
