### ISSUE TITLE
Implementing `whereBetweenSymmetric`?

### ISSUE THREAD

**Issue by kohenkatz** [tpetry/laravel-postgresql-enhanced#32]
Postgres allows adding the `SYMMETRIC` keyword to a `BETWEEN` predicate to make the order of the properties not matter.

For example (from [here](https://til.hashrocket.com/posts/b72090d7a5-between-symmetric-in-postgresql)):

```
select * from generate_series(1,10) as numbers(a)
    where numbers.a between 6 and 3;
 a
---
```

```
select * from generate_series(1,10) as numbers(a)
    where numbers.a between symmetric 6 and 3;
 a
---
 3
 4
 5
 6
```

I would like to add an option to this package to use this feature.

At the simplest level, this includes two functions (similar to `whereLike` that is already in this package):

```
public function whereBetweenSymmetric($column, iterable $values, $boolean = 'and', $not = false)
public function orWhereBetweenSymmetric($column, iterable $values)
```

It probably makes sense to implement it for all of Laravel's other `between`-related methods too, including:

```
public function whereBetweenColumnsSymmetric($column, array $values, $boolean = 'and', $not = false)
public function orWhereBetweenColumnsSymmetric($column, iterable $values)

public function whereNotBetweenSymmetric($column, iterable $values, $boolean = 'and')
public function whereNotBetweenColumnsSymmetric($column, iterable $values, $boolean = 'and')
public function orWhereNotBetweenSymmetric($column, iterable $values)
public function orWhereNotBetweenColumnsSymmetric($column, array $values)

public function havingBetweenSymmetric($column, array $values, $boolean = 'and', $not = false)
```

Thoughts?

**Comment by tpetry** [comment]
I like it! You can draft a PR and I will cleanup, but I currently have very much to do, so I won't be very fast. But this is a very simple change, I could cleanup your draft within an hour.
