### ISSUE TITLE
Wrong type, I think this has to do with implementing the Query/Builder contract. 

### ISSUE THREAD

**Issue by patrickcurl** [tpetry/laravel-postgresql-enhanced#38]
TypeError: Tpetry\PostgresqlEnhanced\Query\Grammar::prependCtes(): Argument #1 ($query) must be of type Tpetry\PostgresqlEnhanced\Query\Builder, Illuminate\Database\Query\Builder given, called in /home/patrick/dev/clients/supermind/laravel/ids-l9/vendor/tpetry/laravel-postgresql-enhanced/src/Query/Grammar.php on line 56

I traced the faulty code to the Bouncer plugin I'm using for auth, but I feel that it shouldn't be on them to necessarily fix bindings. 

So maybe there's something you could do? 

Temporary work around was to just override the file, via PSR4. 

Here's what the faulty function looks like: 
```php
/**
     * Get a new query builder instance.
     *
     * @param  string  $table
     * @return \Illuminate\Database\Query\Builder
     */
    public static function query($table)
    {
        // $query = new \Tpetry\PostgresqlEnhanced\Query\Builder( --- uncomment this to fix. 
        $query = new Builder(
            $connection = static::user()->getConnection(),
            $connection->getQueryGrammar(),
            $connection->getPostProcessor()
        );

        return $query->from(static::table($table));
    }
```

I was thinking there'd be a nice way to bind the default Builder to the new enhanced one, but I'm not as good with IOC, and tried a bunch of different things with bindings/singletons but couldn't get it to play nice. 

Tentatively another fix was to modify prependCtes() method , adding use Illuminate\Database\Query\Builder as BaseBuilder; and modifying the method call like so:
```php
/**
     * Prepend common table expression sql to query.
     */
    private function prependCtes(Builder|BaseBuilder $query, string $sql) : string
    {
        if (\filled($query->expressions)) {
            $with = $this->compileExpressions($query, $query->expressions);

            $sql = "{$with} {$sql}";
        }

        return $sql;
    }```

This fix though works but gives the following warning: 

```
PHP Warning:  Undefined property: Illuminate\Database\Query\Builder::$expressions in /home/patrick/dev/clients/supermind/laravel/ids-l9/vendor/tpetry/laravel-postgresql-enhanced/src/Query/GrammarCte.php on line 42
```

Method to duplicate:

```bash
laravel new testapp
composer require tpetry/laravel-postgresql-enhanced
composer require silber/bouncer
php artisan vendor:publish
# setup db/env. 
# create user and fully setup Bouncer
add method to User model: 
public static function bouncerTest()
    {
        $u = self::first();

        return Bouncer::assign('superadmin')->to($u);
    }
```

**Comment by tpetry** [comment]
Can you create a repository with everything preconfigured so I can debug it? I don‘t know the bouncer plugin and don‘t habe the tome nor I am willing to learn it for trying to reproduce the issue.

**Comment by tpetry** [comment]
I've fixed this with `0.20.1`. Nevertheless, the bouncer implementation should not create builders by itself but just get one from the database connection.

**Comment by Sergiobop** [comment]
I don't know if this is related @tpetry 

```
Tpetry\PostgresqlEnhanced\Query\Grammar::prependCtes(): Argument #1 ($query) must be of type Tpetry\PostgresqlEnhanced\Query\Builder, Staudenmeir\LaravelCte\Query\Builder given, called in vendor/tpetry/laravel-postgresql-enhanced/src/Query/Grammar.php on...: Tpetry\\PostgresqlEnhanced\\Query\\Grammar::prependCtes(): Argument #1 ($query) must be of type Tpetry\\PostgresqlEnhanced\\Query\\Builder, Staudenmeir\\LaravelCte\\Query\\Builder given, called in vendor/tpetry/laravel-postgresql-enhanced/src/Query/Grammar.php on line 54 at vendor/tpetry/laravel-postgresql-enhanced/src/Query/GrammarCte.php:36)
```

I have this errors after installing https://github.com/staudenmeir/laravel-adjacency-list

**Comment by tpetry** [comment]
You encountered a common obstacle in Laravel: only one package can extend the database driver. As the adjacency-list plugin requires `staudenmeier/laravel-cte` it is in parts overwriting my code. You can only use either one. You could fork that package and reduce the dependency to the cte implementation and check whether everything still works correctly. My implementation for CTEs is very similar to the one of staudenmeier for compatibility reasons, maybe it'll work.
