### ISSUE TITLE
Table inheritance

### ISSUE THREAD

**Issue by henriquecm** [tpetry/laravel-postgresql-enhanced#4]
I got interested in Postgres after seeing the post in laravel-news.com, so I was researching differences compared to mysql and saw that you can create make a table inherit another in postgres.

It's possible to do that with this package or that option doesn't exist yet.

**Comment by tpetry** [comment]
Table inheritance is not implemented yet. What is your use case for it?

**Comment by henriquecm** [comment]
I haven't started using postgres yet, I have some possible cases, but I don't know if they are 100% fit for it.
There's one project that I'll starting modelling the db soon, and it's pretty complex so it might come in handy. Specially with things like custom fields.

**Comment by tpetry** [comment]
I am closing this issue as the PostgreSQL wiki advocates to never use table inheritance ([Don't use table inheritance](https://wiki.postgresql.org/wiki/Don%27t_Do_This#Don.27t_use_table_inheritance)). There wasn't any feedback why it is needed in more than a year.

You can always use raw SQL statements to use table inheritance. I plan to only support safe functionality without any hidden problems.
