### ISSUE TITLE
Extended PostgreSQL types are not supported with the Laravel IDE Helper Generator

### ISSUE THREAD

**Issue by patrickcurl** [tpetry/laravel-postgresql-enhanced#40]
When running composer update which regenerates ide-helper stubs, I go this as it was analyzing the models. 
```php
Exception: Unknown database type citext requested, Doctrine\DBAL\Platforms\PostgreSQL100Platform may not support it.
Could not analyze class App\Models\Tag.
```

The fix was easy enough, in AppServiceProvider I put: 
```php
<?php
// ...
use Tpetry\PostgresqlEnhanced\Types\CitextType;
class AppServiceProvider extends ServiceProvider
{
...
    public function boot(){
        \app('db')->registerDoctrineType(CitextType::class, 'citext', 'string');
        // ...
    }
```

As I was looking at the code in the vendor folder, I noticed the $typeInstance->getName() is deprecated in doctrine, not sure if that is related,and I'm not sure that's the best way to register the doctrine type, but it made the error go away..

**Comment by tpetry** [comment]
Hi Patrick, this is not a problem of this driver. Doctrine can not handle many of the PostgreSQL types and will throw that exact exception, it's doing that within Laravel migrations too. I "patched" Laravel migrations by adding many of the missing PostgreSQL types to Doctrine. But the types are currently only added when migrations are executed.

Does it solve the problem when the `registerDoctrineTypes` call is moved to the `register` method and not only called when the migrator is started? Does the stubs generator broadcast a custom event so I could listen for the event to not register the types for every Laravel boot?
https://github.com/tpetry/laravel-postgresql-enhanced/blob/master/src/PostgresqlEnhancedServiceProvider.php#L94

**Comment by patrickcurl** [comment]
@tpetry 
I just installed the spatie/laravel-model-info package, and noticed that somewhere up the chain the citext type didn't persist. 

However, when I changed: 
```
\app('db')->registerDoctrineType(\Tpetry\PostgresqlEnhanced\Types\CitextType::class, 'citext', 'string');
```

to: 
```
$this->app['db']->connection()->getDoctrineSchemaManager()->getDatabasePlatform()->registerDoctrineTypeMapping('citext', 'string');
```

Everything worked. 

I also submitted a PR on that package to just add 'citext' => 'string' to their typeMapping array.  see: https://github.com/spatie/laravel-model-info/pull/15

**Comment by robsontenorio** [comment]
Just place this on ` ide-helper.php` config file

![image](https://user-images.githubusercontent.com/118955/194145990-15a67105-cb72-40dd-86d8-15f4e47dfbea.png)

**Comment by tpetry** [comment]
@patrickcurl Can you try again with `0.25.1`? All artisan commands now have access to the advanced data types.

**Comment by patrickcurl** [comment]
@tpetry i think it's resolved, otherwise I jerry rigged it to work, so I think this can be closed.  Thanks!

**Comment by tpetry** [comment]
Awesome! One problem less when using PG.
