### ISSUE TITLE
Larastan undefined property when accessing model properties

### ISSUE THREAD

**Issue by benbjurstrom** [tpetry/laravel-postgresql-enhanced#43]
Hello,
First off I want to say thank you for all the hard work you've put into this amazing package.

I ran into an issue where Larastan is giving me errors when I access model properties that were defined in migrations using the package's Blueprint class. For example, given the following user migration:
```php
<?php

use Illuminate\Database\Migrations\Migration;
use Tpetry\PostgresqlEnhanced\Schema\Blueprint;
use Tpetry\PostgresqlEnhanced\Support\Facades\Schema;

class CreateUsersTable extends Migration
{
    public function up()
    {
        Schema::create('users', function (Blueprint $table) {
            $table->uuid('id')->primary();
            $table->string('name');
            $table->caseInsensitiveText('email')->unique()->index();
        });
    }
}
```

Calling properties on the model with `$user->name` or `$user->email` will give the following error:

```bash
------ ---------------------------------------------------------- 
  Line   Data/AuthData.php                                         
 ------ ---------------------------------------------------------- 
  49     Access to an undefined property App\Models\User::$name.   
  51     Access to an undefined property App\Models\User::$email.  
 ------ ---------------------------------------------------------- 
```

It's easy enough to work around by annotating the model.
```php
/**
 * @property string $name
 * @property string $email
 */
class User extends Authenticatable
```

But since I'm using the package's phpstan extension I figured I'd ask if this is expected functionality or if I'm missing something obvious.

Thanks again!

---
#### Environment Details

composer.json
```json
"php": "^8.1",
"laravel/framework": "^9.43",
"nunomaduro/larastan": "^2.2.9",
"tpetry/laravel-postgresql-enhanced": "^0.23.0"
```

phpstan.neon
```yaml
includes:
    - ./vendor/nunomaduro/larastan/extension.neon
    - ./vendor/tpetry/laravel-postgresql-enhanced/phpstan-extension.neon

parameters:
    level: 8
```

**Comment by tpetry** [comment]
Is the name property correctly detected if you use Laravel‘s blueprint and schema classes? You have to temporary use a string column for `email` to test it?

**Comment by benbjurstrom** [comment]
The migrations are in the default location under database/migrations and it's correctly detected when using Laravel's blueprint class. I was already using Larastan in my app and it only started giving errors when I added this package's Blueprint class to a few migrations. 

I was able to reproduce the issue on a fresh Laravel install:
https://github.com/benbjurstrom/laravel-issues

In the example repo above, the `users` migration uses the blueprint class from this package and the `posts` migration uses the Laravel one. In the app the table properties are accessed in `app/Data/UserData.php` and `app/Data/PostData.php` respectively.

If you run
```bash
git clone https://github.com/benbjurstrom/laravel-issues.git
composer install
cd laravel-issues
php vendor/bin/phpstan analyse -c ./phpstan.neon
```

You get errors for accessing unknown User properties but not for Post.
```bash
 ------ ---------------------------------------------------------- 
  Line   Data/UserData.php                                         
 ------ ---------------------------------------------------------- 
  19     Access to an undefined property App\Models\User::$name.   
  20     Access to an undefined property App\Models\User::$email.  
 ------ ---------------------------------------------------------- 
```

When testing this out one thing I've noticed is you sometimes don't see changes until you clear the phpstan cache with `vendor/bin/phpstan clear-result-cache`

Appreciate you taking a look. As I mentioned for now I can work around this by annotating the model so it's not super urgent.

**Comment by tpetry** [comment]
@canvural Could it be that the larastan code checks for a specific class to be used and can't work with a class extending the default Laravel one? The `email` issue is totally understandable as Larastan doesn't know how to handle it. Could a plugin add those definitions?

**Comment by tpetry** [comment]
I've worked on a fix to Larastan so that Eloquent attributes are still detected when my schema migrations are used (nunomaduro/larastan#1485).

As the Larastan package won't know the type information of these columns, they are `mixed` instead of a more correct one. So annotations are still needed for the `email` column to identify them as `string` correctly. The idea of @canvural could be implemented to add aliases but I am planning to add custom types soon and the suggested approach would fail there. So I will not go further that way, having them identified as `mixed` by default is enough for me.

**Comment by tpetry** [comment]
With the newest Larastan release all PostgreSQL migration blueprints are now handled correctly.
