### ISSUE TITLE
New name

### ISSUE THREAD

**Issue by szepeviktor** [tpetry/laravel-postgresql-enhanced#62]
_Laravel PostgreSQL Enhanced_ suggests it has something to do with the company behind the Laravel framework.

"Enhanced PostgreSQL for Laravel"
or "PostgreSQL Enhancements for Laravel"

What do you think?

**Comment by szepeviktor** [comment]
Although naming packages $BRAND-$FUNCTION is highly popular!

**Comment by mstaack** [comment]
naming is fine. i would recommend to just stick with the current schema 😜

**Comment by szepeviktor** [comment]
All right, all right.

**Comment by tpetry** [comment]
I am open to naming changes but I don't really give the package a recognizable on the docs. It is just described by it behavior. The only real usage that could be changed is the composer name - and I won't change that as there is already quite a sizeable install base using that name.

It would be a change without giving any benefits.

**Comment by szepeviktor** [comment]
I just wanted to plant this thought in your head.
