### ISSUE TITLE
Adding support for bytea columns

### ISSUE THREAD

**Issue by kevin-cyster-rocketseed** [tpetry/laravel-postgresql-enhanced#69]
Firstly, thank you for your brilliant work.

After using your package to access some of the functionality that the core laravel packages do not possess, I have discovered that even your package does not cater for Bytea columns.

As per this comment [https://github.com/laravel/framework/issues/10847#issuecomment-512612353](https://github.com/laravel/framework/issues/10847#issuecomment-512612353)  (which I have tested locally) and is available in the fork [https://github.com/Rocketseed-Development/laravel-postgresql-enhanced](https://github.com/Rocketseed-Development/laravel-postgresql-enhanced).

I propose adding the following function to PostgresEnhancedConnection.php

`
/**
 * Modify the bindValues function to cater for Bytea
 * 
 * @param \PDOStatement $statement
 * @param Array $bindings
 * @return void
 */
public function bindValues($statement, $bindings)
{
    foreach ($bindings as $key => $value) {
        $statement->bindValue(
            is_string($key) ? $key : $key + 1,
            $value, 
            is_int($value) || is_float($value) ?
           PDO::PARAM_INT :
          ($value === null || ctype_print($value) ? PDO::PARAM_STR : PDO::PARAM_LOB)
        );
    }
}
`

**Comment by tpetry** [comment]
My expressions package has a value type. Can you try whether using the value in binary mode will solve the problem`

```php
new Value('....', binary: true)
```

**Comment by kevin-cyster-rocketseed** [comment]
> My expressions package has a value type. Can you try whether using the value in binary mode will solve the problem`
> 
> ```
> new Value('....', binary: true)
> ```

Thank you for your reply.

I added your other package tpetry/laravel-query-expressions to my project and defined the Bytea field as explained.

Yes. The binary mode does seem to solve the problem with inserting into the table.

I'm currently running some more tests just to make sure that the stream can be converted back to an image

**Comment by tpetry** [comment]
Awesome, so it works as expected.
