### ISSUE TITLE
IDE autocomplete

### ISSUE THREAD

**Issue by vatsake** [tpetry/laravel-postgresql-enhanced#71]
How does one make IDE understand `Tpetry\PostgresqlEnhanced\Query\Builder` methods?

:)

**Comment by tpetry** [comment]
This is something I am unhappy with for a long time. But I don't know how to fix it 🤷‍♂️

Recently, Laravel Idea shared that they will support this with their next update [0]. But I don't know any approach for VSCode or PHP Storm without the plugin.

[0] https://x.com/laravel_idea/status/1755279230210904084?s=20

**Comment by boris-glumpler** [comment]
I've added a `.phpstorm.meta.php` file to my project root with the following contents:

```php
<?php

declare(strict_types=1);

namespace Illuminate\Database\Eloquent {
    /**
     * @mixin \Tpetry\PostgresqlEnhanced\Query\Builder
     */
    class Builder {}
}

namespace PHPSTORM_META {
    //metadata directives
}
```

**Comment by tpetry** [comment]
Hmm, but that file would still need to be copied. And potentially conflicts with other packages wanting to do the same. Would be awesome if it could be at the root dir of every package in the vendor dir. So, every package could provide their own always-updated definitions.

**Comment by boris-glumpler** [comment]
Yup, this isn't a solution for packages and def feels hacky, but it's worked well for me. Be good when Laravel Idea supports this, tho!

**Comment by tpetry** [comment]
@vatsake @boris-glumpler Are you using PhpStorm with Laravel Idea? In that case you could test the open Pull Request which should do a full integration with auto-suggestions and jump-to-code.

**Comment by boris-glumpler** [comment]
Yup, I do. I've just finished a hike in a pretty remote part of Nepal, tho, and it'll take me 2-3 days to get back to my laptop. Will try it out then.

**Comment by tpetry** [comment]
Ok, then I'll test on the weekend again.

**Comment by tpetry** [comment]
Autocomplete for PhpStorm with Laravel Idea plugin is now live with `0.35.0`.

Other IDEs or PhpStorm without the plugin are not supported as there are no ways to do this currently. But I've requested the Laravel IDE helper package to make this possible in the future with a generic way: barryvdh/laravel-ide-helper#1529
