### ISSUE TITLE
Declaration of BuilderWhere::orWhereAll must be compatible with Illuminate\Database\Query\Builder::orWhereAll

### ISSUE THREAD

**Issue by CodeLieutenant** [tpetry/laravel-postgresql-enhanced#76]
This error manifested itself on `artisan vendor:publish --tag=laravel-assets`, I don't know really why there, but it looks like some package does something with the database at publishing.

I've checked there are many methods like this, that are not compatible with Laravel's Eloquent Builder. The problem is (I think) trait overriding methods when extending the base Eloquent Builder. 

It's nice to have types in the codebase, but unfortunately, we should wait for Laravel to add those types to the Builder.

```
Declaration of Tpetry\PostgresqlEnhanced\Query\BuilderWhere::orWhereAll($column, string $operator, Traversable|array $values): static must be compatible with Illuminate\Database\Query\Builder::orWhereAll($columns, $operator = null, $value = null)
```

Laravel version: 10.47
PHP version: 8.3
laravel-postgresql-enhanced version: 0.35

PS. If you are ok with it, I would like to make these changes to the library.
Also thank you for this AWESOME piece of software, really makes life a lot easier using Postgres Database.

**Comment by tpetry** [comment]
Laravel added their own `whereAll` method yesterday. I‘ll have to look tomorrow how to fix it. Will probably be a breaking change. I‘ve expected this problem to happen for so long. Its interesting that it is only happening after almost three years.

**Comment by CodeLieutenant** [comment]
Thanks for a such quick reply.

For everyone who encounters the same problem, just lock Laravel in `composer.json` to `v10.46` until the issue is resolved by @tpetry.

**Comment by tpetry** [comment]
I had to rename some methods to not conflict with Laravel 10.47 anymore. If you upgrade to 0.36.0 everything will work correctly again 😉

Renamed query builder methods:
* `whereAll` -> `whereAllValues`
* `whereNotAll` -> `whereNotAllValues`
* `orWhereAll` -> `orWhereAllValues`
* `orWhereNotAll` -> `orWhereNotAllValues`
* `whereAny` -> `whereAnyValue`
* `whereNotAny` -> `whereNotAnyValue`
* `orWhereAny` -> `orWhereAnyValue`
* `orWhereNotAny` -> `orWhereNotAnyValue`
