### ISSUE TITLE
Compatibility Issue with whereAll and whereAny Methods in Laravel 10.47.0

### ISSUE THREAD

**Issue by bayukartiko** [tpetry/laravel-postgresql-enhanced#77]
The recent update to Laravel (version 10.47.0) introduced a new feature ([#76](https://github.com/laravel/framework/pull/50344)) which has caused compatibility issues with the whereAll and whereAny methods in this package.

As a result of this update, attempting to use these methods in the application results in the following error being thrown:
```
Declaration of Tpetry\\PostgresqlEnhanced\\Query\\BuilderWhere::orWhereAll($column, ?string $operator, ?iterable $values): static must be compatible with Illuminate\\Database\\Query\\Builder::orWhereAll($columns, $operator = null, $value = null)
```

To temporarily address this issue, I have manually disabled the affected feature within the package, thus resolving the error.

I hope this issue will be fixed ASAP to ensure seamless compatibility with the latest version of Laravel. Thank you.

**Comment by tpetry** [comment]
This has already been reported in #76 and is fixed with the newest release.
