### ISSUE TITLE
[QUESTION] Read and Write Connections

### ISSUE THREAD

**Issue by wit3** [tpetry/laravel-postgresql-enhanced#78]
Hi, it's possibile to define a read/write connection in pgsql connection?

in the official docs it's listed only mysql

- https://laravel.com/docs/10.x/database#read-and-write-connections

EDIT : 
I've found an old issue in framework repo dated 2015, hoping for a PR
- https://github.com/laravel/framework/issues/6880

**Comment by tpetry** [comment]
The Laravel driver does not differentiate for this logic which database is used. The PG driver in Laravel should work. And my extensions therefore should also work.

**Comment by wit3** [comment]
Unfortunately doesn't work, if i defined the read/write array like the example, only the write is used even if i use the 
```php
'pgsql' => [
    'read' => [
        'host' => [
            '192.168.1.1',
            '196.168.1.2',
        ],
    ],
    'write' => [
        'host' => [
            '196.168.1.3',
        ],
    ],
    'driver' => 'pgsql',
    'database' => 'database',
    'username' => 'root',
    'password' => '',
    'prefix' => '',
    'prefix_indexes' => true,
    'search_path' => 'adascat',
    'sslmode' => 'prefer',
],

```

```php
User::on('pgsql::read')->find(1);
```
or
```php
 DB::connection("pgsql::read")
   ->table("users")
   ->select("name", "email as user_email")
   ->get();
```

**Comment by tpetry** [comment]
Ok, then please raise an issue in the Laravel repo. I extend the Laravel driver and have no plan implementing this by myself.
