### ISSUE TITLE
Search in json or text field

### ISSUE THREAD

**Issue by aeq-dev** [tpetry/laravel-postgresql-enhanced#8]
Hello @tpetry,
Thanks for this useful package,
I'm using this package [spatie translatable](https://github.com/spatie/laravel-translatable)
How could I search in text field something like this :
`$query->where('name->fr', 'ilike', '%' . $term . '%'))`
Name field has a structure :
`{"en":"Hello","fr":"Salut"}`

Thanks

**Comment by tpetry** [comment]
My package does not change any behaviour. The completely valid approach of Laravel you posted does still work.
