### ISSUE TITLE
Support `inet` column type

### ISSUE THREAD

**Issue by devfrey** [tpetry/laravel-postgresql-enhanced#83]
I noticed `cidr` is supported out of the box (`ipNetwork()`), but I intend to store host IP addresses only (for which `inet` is better suited). I would be happy to create a PR to add a column definition to the blueprint.

Thank you for providing this great package! I've found it to be very useful.

**Comment by tpetry** [comment]
You should use the `ipAddress` type of Laravel which is creating `inet` columns for PostgreSQL 😉

**Comment by devfrey** [comment]
> You should use the `ipAddress` type of Laravel which is creating `inet` columns for PostgreSQL 😉

Can't believe I missed that, thanks!
