### ISSUE TITLE
Using newEloquentBuilder in model to extend query builder results in: must be of type Illuminate\Database\ConnectionInterface

### ISSUE THREAD

**Issue by kdevan** [tpetry/laravel-postgresql-enhanced#97]
With some code like this in the model:

```php
/**
 * @param  \Illuminate\Database\Query\Builder  $query
 * @return UserQueryBuilder<User>
 */
public function newEloquentBuilder($query): UserQueryBuilder
{
    return new UserQueryBuilder($query);
}
```

And a custom Query Builder that looks like this:

```php
use Tpetry\PostgresqlEnhanced\Query\Builder;

/**
 * @template TModelClass of User
 *
 * @extends Builder<TModelClass>
 */
class UserQueryBuilder extends Builder {}
```

I get the error: 

`"Illuminate\Database\Query\Builder::__construct(): Argument #1 ($connection) must be of type Illuminate\Database\ConnectionInterface, Tpetry\PostgresqlEnhanced\Query\Builder given, called in /app/api/app/Models/User.php on line 263"`

So the error is in the model on this line: 

```php
return new UserQueryBuilder($query);
```

If I change the query builder to extend the Laravel Eloquent Query Builder like this it works:

```php
use Illuminate\Database\Eloquent\Builder;

/**
 * @template TModelClass of User
 *
 * @extends Builder<TModelClass>
 */
class UserQueryBuilder extends Builder {}
```

But then later in actual business logic in a controller or something I get this message: 

`Call to undefined method Tpetry\PostgresqlEnhanced\Query\Builder::customQueryBuilderFunction()`

None of my custom functions in the custom query builder are working because of this error.

This used to work when I had the custom query builder extending the Eloquent Builder before, so that last error is a new one for me from some update, not necessarily this library. But I wonder if you have a recommendation for working with custom query builders? I always wanted to be able to extend your builder as that seemed like the right way to do it, but could never get that working because of the `ConnectionInterface` error.

Gonna keep digging into this for now, I'll update here if I figure anything out!

**Comment by tpetry** [comment]
Can you create a simple demo repository I can checkout to research the bug?

**Comment by tpetry** [comment]
It will be impossible to use both libraries at the same time. The Adjacency list package is using the CTE package by staudenmeier - which is extending Eloquent by replacing internal Laravel logic like my package. And only package can do this at the same time. Sorry, there's nothing we can do to solve this problem.

But someone was able to get it working with the adjacency list package: https://github.com/tpetry/laravel-postgresql-enhanced/issues/42#issuecomment-1574539714

**Comment by tpetry** [comment]
You have to extend my query builder instead of the Laravel one ;)

**Comment by tpetry** [comment]
can you make a small demo repository that i can look into this? Actually my QueryBuilder is the same as the Laravel one - just some more stuff added to it.

**Comment by tpetry** [comment]
Thanks, I'll dig into that later.

**Comment by tpetry** [comment]
Ok, I was wrong. You just extend the normal Eloquent Builder from Laravel and everything works. All stuff added by my package is also automatically available to you this way.

I thought I've added a custom eloquent builder - but that was probably an experiment which I had to discard because of compatibility issues.
