### ISSUE TITLE
Fatal Error with Laravel 11.23.4

### ISSUE THREAD

**Issue by coolamit** [tpetry/laravel-postgresql-enhanced#98]
Hi

It seems something broke with Laravel v11.23.4 release. I'm coming across this error after I ran `composer update` to pull in updated Laravel & `laravel-postgresql-enhanced` packages.

<img width="1426" alt="image" src="https://github.com/user-attachments/assets/baaf0b84-a86f-4843-8821-d4572a1ab79b">

**Comment by coolamit** [comment]
@tpetry FYI

**Comment by tpetry** [comment]
Are you on the newest version? The `whereLike` issue has been fixed with the new v1 stable release.

**Comment by coolamit** [comment]
> Are you on the newest version? The `whereLike` issue has been fixed with the new v1 stable release.

Ah. `composer update` pulled in the last minor version from the `0.4.x` branch. I did the `composer require tpetry/laravel-postgresql-enhanced` again to pull in the 1.x branch & now all seems to be working. Thanks.
